<?php
function handle_action(string $action):void{
 if($_SERVER['REQUEST_METHOD']!=='POST')redirect('?page=dashboard'); verify_csrf();
 switch($action){
 case 'login': global $config; if(hash_equals($config['admin_email'],postv('email'))&&hash_equals($config['admin_password'],postv('password'))){$_SESSION['authenticated']=true;$_SESSION['email']=$config['admin_email'];flash('success','Signed in.');redirect('?page=dashboard');}flash('error','Invalid credentials.');redirect('?page=login');
 case 'logout': session_destroy();redirect('?page=login');
 case 'create_mission':$id=db_insert('missions',['title'=>postv('title'),'instruction'=>postv('instruction'),'status'=>'DRAFT']);audit('mission.created','mission',$id,['instruction'=>postv('instruction')]);flash('success','Mission created.');redirect('?page=missions');
 case 'run_mission':$id=(int)($_POST['id']??0);$m=db_find('missions',$id);if(!$m)redirect('?page=missions');$r=ai_chat('You are the NEXA Orchestrator. Convert a business mission into a structured execution plan. Respect source permissions and never propose unauthorized scraping.',$m['instruction']);db_update('missions',$id,fn($x)=>$x+['status'=>'COMPLETED','result_json'=>json_encode(['result'=>$r['text'],'demo'=>$r['demo']??false],JSON_UNESCAPED_UNICODE)]);audit('mission.executed','mission',$id,$r);flash('success','Mission executed.');redirect('?page=missions');
 case 'create_company':$id=db_insert('companies',['name'=>postv('name'),'industry'=>postv('industry'),'location'=>postv('location'),'website'=>postv('website'),'size'=>postv('size'),'description'=>postv('description'),'source_type'=>'manual','source_url'=>postv('source_url'),'confidence'=>0.9]);audit('company.created','company',$id);flash('success','Company added.');redirect('?page=companies');
 case 'import_csv':if(!isset($_FILES['csv'])||$_FILES['csv']['error']!==UPLOAD_ERR_OK){flash('error','CSV upload failed.');redirect('?page=companies');}$fh=fopen($_FILES['csv']['tmp_name'],'r');$header=fgetcsv($fh);$n=0;while(($row=fgetcsv($fh))!==false){$map=[];foreach($header as $i=>$h)$map[strtolower(trim($h))]=$row[$i]??'';if(trim($map['name']??'')){db_insert('companies',['name'=>trim($map['name']),'industry'=>trim($map['industry']??''),'location'=>trim($map['location']??''),'website'=>trim($map['website']??''),'description'=>trim($map['description']??''),'source_type'=>'csv_import','source_url'=>trim($map['source_url']??''),'confidence'=>0.85]);$n++;}}fclose($fh);audit('company.csv_import','company',null,['count'=>$n]);flash('success',"Imported {$n} companies.");redirect('?page=companies');
 case 'create_contact':$id=db_insert('contacts',['company_id'=>(int)($_POST['company_id']??0),'name'=>postv('name'),'title'=>postv('title'),'email'=>postv('email'),'phone'=>postv('phone'),'linkedin_url'=>postv('linkedin_url'),'source_url'=>postv('source_url'),'consent_status'=>postv('consent_status','unknown')]);audit('contact.created','contact',$id);flash('success','Contact added.');redirect('?page=contacts');
 case 'create_lead':$id=db_insert('leads',['company_id'=>(int)($_POST['company_id']??0),'contact_id'=>(int)($_POST['contact_id']??0),'business_type'=>postv('business_type'),'status'=>postv('status','NEW'),'signal'=>postv('signal'),'score'=>(int)($_POST['score']??0),'score_explanation'=>postv('score_explanation'),'source_type'=>'manual','source_url'=>postv('source_url'),'notes'=>postv('notes')]);audit('lead.created','lead',$id);flash('success','Lead added.');redirect('?page=leads');
 case 'generate_outreach':$lead=find_lead_joined((int)$_POST['id']);if(!$lead)redirect('?page=leads');$text=ai_generate_outreach($lead);$id=db_insert('messages',['lead_id'=>$lead['id'],'direction'=>'outbound','channel'=>'email','subject'=>'Partnership opportunity for '.$lead['company_name'],'body'=>$text,'status'=>'DRAFT']);audit('outreach.generated','message',$id,['lead_id'=>$lead['id']]);flash('success','Outreach draft generated.');redirect('?page=inbox');
 case 'send_message':$id=(int)$_POST['id'];$msg=db_find('messages',$id);if(!$msg)redirect('?page=inbox');$lead=find_lead_joined((int)$msg['lead_id']);$email=$lead['email']??'';$blocked=count(db_where('suppression_list',fn($r)=>strcasecmp((string)$r['value'],$email)===0))>0;if($blocked||($lead['consent_status']??'unknown')==='blocked'){flash('error','Blocked by suppression/compliance rule.');redirect('?page=inbox');}if(function_exists('mail')&&filter_var($email,FILTER_VALIDATE_EMAIL)&&!$GLOBALS['config']['demo_mode'])@mail($email,$msg['subject'],$msg['body'],'From: '.$GLOBALS['config']['from_email'].'\r\nContent-Type: text/plain; charset=UTF-8\r\n');db_update('messages',$id,fn($x)=>$x+['status'=>'SENT','sent_at'=>date('Y-m-d H:i:s')]);db_update('leads',(int)$lead['id'],fn($x)=>$x+['status'=>'CONTACTED','last_contact_at'=>date('Y-m-d H:i:s'),'next_follow_up_at'=>date('Y-m-d H:i:s',strtotime('+3 days'))]);audit('message.sent','message',$id);flash('success','Message marked SENT. Configure your mail provider for real delivery.');redirect('?page=inbox');
 case 'create_document':$type=postv('doc_type','QUOTATION');$id=db_insert('documents',['doc_type'=>$type,'number'=>next_doc_number($type),'company_id'=>(int)($_POST['company_id']??0),'lead_id'=>(int)($_POST['lead_id']??0),'status'=>'DRAFT','payload'=>json_encode(['description'=>postv('description'),'payment_terms'=>postv('payment_terms'),'validity_days'=>(int)($_POST['validity_days']??14)],JSON_UNESCAPED_UNICODE),'total'=>(float)($_POST['total']??0)]);audit('document.created','document',$id);flash('success',$type.' created.');redirect('?page=documents');
 case 'create_property':$id=db_insert('properties',['title'=>postv('title'),'property_type'=>postv('property_type'),'location'=>postv('location'),'price'=>(float)($_POST['price']??0),'land_size'=>(float)($_POST['land_size']??0),'building_size'=>(float)($_POST['building_size']??0),'seller_type'=>postv('seller_type'),'source'=>postv('source','manual'),'source_url'=>postv('source_url'),'status'=>'NEW','description'=>postv('description')]);audit('property.created','property',$id);flash('success','Property added.');redirect('?page=properties');
 case 'create_vendor':$id=db_insert('vendors',['name'=>postv('name'),'category'=>postv('category'),'location'=>postv('location'),'website'=>postv('website'),'contact'=>postv('contact'),'source'=>postv('source','manual'),'notes'=>postv('notes')]);audit('vendor.created','vendor',$id);flash('success','Vendor added.');redirect('?page=vendors');
 case 'create_content':$id=db_insert('content_items',['entity_type'=>postv('entity_type'),'entity_id'=>(int)($_POST['entity_id']??0),'channel'=>postv('channel'),'title'=>postv('title'),'body'=>postv('body'),'status'=>'DRAFT','scheduled_at'=>postv('scheduled_at')]);audit('content.created','content',$id);flash('success','Content draft created.');redirect('?page=content');
 case 'add_suppression':$value=postv('value');if($value!==''){$exists=db_where('suppression_list',fn($r)=>strcasecmp((string)$r['value'],$value)===0);if(!$exists)db_insert('suppression_list',['value'=>$value,'reason'=>postv('reason')]);}audit('suppression.added','suppression');flash('success','Suppression rule saved.');redirect('?page=settings');
 case 'save_integration':$provider=postv('provider');$rows=db_where('integrations',fn($r)=>($r['provider']??'')===$provider);if($rows)db_update('integrations',(int)$rows[0]['id'],fn($x)=>$x+['status'=>isset($_POST['enabled'])?'CONFIGURED':'NOT_CONNECTED','config_json'=>json_encode(['notes'=>postv('notes')])]);else db_insert('integrations',['provider'=>$provider,'status'=>isset($_POST['enabled'])?'CONFIGURED':'NOT_CONNECTED','config_json'=>json_encode(['notes'=>postv('notes')])]);audit('integration.updated','integration',null,['provider'=>$provider]);flash('success','Integration saved.');redirect('?page=integrations');
 }
}
