<?php
function blank_store(): array {
    return ['companies'=>[],'contacts'=>[],'leads'=>[],'opportunities'=>[],'campaigns'=>[],'campaign_steps'=>[],'messages'=>[],'tasks'=>[],'appointments'=>[],'documents'=>[],'properties'=>[],'vendors'=>[],'content_items'=>[],'automations'=>[],'missions'=>[],'integrations'=>[],'audit_logs'=>[],'suppression_list'=>[]];
}
function db(): array {
    global $config,$db_store;
    if (isset($db_store) && is_array($db_store)) return $db_store;
    $file=$config['data_path']; if(!is_dir(dirname($file)))mkdir(dirname($file),0775,true);
    if(!file_exists($file)){$db_store=blank_store();save_db($db_store);return $db_store;}
    $data=json_decode(file_get_contents($file),true);$db_store=is_array($data)?$data:blank_store();foreach(blank_store() as $k=>$v)if(!isset($db_store[$k])||!is_array($db_store[$k]))$db_store[$k]=[];return $db_store;
}
function save_db(?array $data=null):void{global $config,$db_store;if($data!==null)$db_store=$data;file_put_contents($config['data_path'],json_encode($db_store??blank_store(),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX);}
function next_id(string $table):int{$d=db();$max=0;foreach($d[$table] as $r)$max=max($max,(int)($r['id']??0));return $max+1;}
function db_insert(string $table,array $row):int{global $db_store;$d=db();$id=next_id($table);$row=['id'=>$id,'created_at'=>$row['created_at']??date('Y-m-d H:i:s')]+$row;$d[$table][]=$row;$db_store=$d;save_db();return $id;}
function db_all(string $table):array{$d=db();return $d[$table]??[];}
function db_find(string $table,int $id):?array{foreach(db_all($table) as $r)if((int)($r['id']??0)===$id)return $r;return null;}
function db_where(string $table,callable $predicate):array{$out=[];foreach(db_all($table) as $r)if($predicate($r))$out[]=$r;return $out;}
function db_update(string $table,int $id,callable $mutator):bool{global $db_store;$d=db();foreach($d[$table] as &$r){if((int)$r['id']===$id){$r=$mutator($r);$r['updated_at']=date('Y-m-d H:i:s');$db_store=$d;save_db();return true;}}return false;}
function db_delete(string $table,int $id):bool{global $db_store;$d=db();$before=count($d[$table]);$d[$table]=array_values(array_filter($d[$table],fn($r)=>(int)$r['id']!==$id));if(count($d[$table])<$before){$db_store=$d;save_db();return true;}return false;}
function db_count(string $table,?callable $pred=null):int{return $pred?count(db_where($table,$pred)):count(db_all($table));}
function db_sum(string $table,string $field,?callable $pred=null):float{$rows=$pred?db_where($table,$pred):db_all($table);$s=0;foreach($rows as $r)$s+=(float)($r[$field]??0);return $s;}
function db_sort_desc(array $rows,string $field='id'):array{usort($rows,fn($a,$b)=>strcmp((string)($b[$field]??''),(string)($a[$field]??'')));return $rows;}
function db_sort_asc(array $rows,string $field='id'):array{usort($rows,fn($a,$b)=>strcmp((string)($a[$field]??''),(string)($b[$field]??'')));return $rows;}
function init_db(array &$data):void{if(db_count('companies')===0)seed_defaults();}
function seed_defaults():void{db_insert('companies',['name'=>'PT Example Manufacturing','industry'=>'Manufacturing','location'=>'Semarang, Central Java','website'=>'https://example.com','size'=>'500-1000','description'=>'Example production company for demo.','source_type'=>'demo','source_url'=>'https://example.com','confidence'=>0.95]);db_insert('companies',['name'=>'PT Example Plantation','industry'=>'Plantation','location'=>'Central Kalimantan','website'=>'https://example.org','size'=>'1000+','description'=>'Example plantation company for demo.','source_type'=>'demo','source_url'=>'https://example.org','confidence'=>0.92]);db_insert('companies',['name'=>'ABC Property Owner','industry'=>'Property','location'=>'Bandung, West Java','website'=>'','size'=>'1','description'=>'House listing owner demo.','source_type'=>'user_import','source_url'=>'','confidence'=>0.9]);db_insert('contacts',['company_id'=>1,'name'=>'Sarah HR','title'=>'HR Manager','email'=>'hr@example.com','phone'=>'+628120000001','source_url'=>'https://example.com/careers','consent_status'=>'unknown']);db_insert('contacts',['company_id'=>2,'name'=>'Budi Talent','title'=>'Recruitment Manager','email'=>'talent@example.org','phone'=>'+628120000002','source_url'=>'https://example.org/careers','consent_status'=>'unknown']);db_insert('leads',['company_id'=>1,'contact_id'=>1,'business_type'=>'Recruitment','status'=>'QUALIFIED','signal'=>'8 open positions and expansion signal','score'=>89,'score_explanation'=>'Strong company fit and active hiring signal.','source_type'=>'demo','source_url'=>'https://example.com/careers','notes'=>'Demo lead']);db_insert('leads',['company_id'=>2,'contact_id'=>2,'business_type'=>'Recruitment','status'=>'NEW','signal'=>'Multiple engineering and operator vacancies','score'=>76,'score_explanation'=>'Relevant hiring demand detected.','source_type'=>'demo','source_url'=>'https://example.org/careers','notes'=>'Demo lead']);db_insert('opportunities',['lead_id'=>1,'title'=>'Recruitment Support - PT Example Manufacturing','value'=>25000000,'stage'=>'PROPOSAL','probability'=>60]);db_insert('opportunities',['lead_id'=>2,'title'=>'Recruitment Support - PT Example Plantation','value'=>15000000,'stage'=>'QUALIFIED','probability'=>25]);db_insert('properties',['title'=>'Rumah Strategis Bandung','property_type'=>'House','location'=>'Bandung, West Java','price'=>950000000,'land_size'=>120,'building_size'=>90,'seller_type'=>'Owner Direct','source'=>'demo','source_url'=>'','status'=>'NEW','description'=>'3 bedroom house demo listing suitable for agent outreach.']);db_insert('vendors',['name'=>'Demo Printing Vendor','category'=>'Printing','location'=>'Semarang, Central Java','website'=>'https://example.net','contact'=>'sales@example.net','source'=>'demo','notes'=>'Demo vendor record.']);}
